/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SCD2_2021_Exam.server;


import GameQRcodeMaker.Server.dummyImgur;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class dummyImgurTest {
    @Test
    public void dummyImgur(){
        String a = dummyImgur.doPost();
        assertEquals(a,"{\"data\":{\"id\":\"ERJiS51\",\"title\":null,\"description\":null,\"datetime\":1623150769,\"type\":\"image\\/jpeg\",\"animated\":false,\"width\":500,\"height\":500,\"size\":68491,\"views\":0,\"bandwidth\":0,\"vo\n" +
                "te\":null,\"favorite\":false,\"nsfw\":null,\"section\":null,\"account_url\":null,\"account_id\":0,\"is_ad\":false,\"in_most_viral\":false,\"has_sound\":false,\"tags\":[],\"ad_type\":0,\"ad_url\":\"\",\"edite\n" +
                "d\":\"0\",\"in_gallery\":false,\"deletehash\":\"SABU5icwP2CqmuZ\",\"name\":\"\",\"link\":\"Imgur Offline\"},\"success\":true,\"status\":200}\n");

    }


}
