/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SCD2_2021_Exam.server;


import GameQRcodeMaker.Server.imgur;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class imgurTest {
    @Test
    public void imgur(){
        String a = imgur.doPost("google.com","zto");
        assertEquals(a,"");
    }



}
