/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GameQRcodeMaker;


import GameQRcodeMaker.UI.ui;

public class App {

    public static boolean inputOnline;
    public static boolean outputOnline;

    public static void main(String[] args) throws Exception {

        if(args[0].equals("offline")){
            inputOnline = false;
        }else if (args[0].equals("online")){
            inputOnline = true;
        }else {
            throw new IllegalArgumentException("Only online or offline version");
        }
        if (args[1].equals("offline")){
            outputOnline = false;
        }else if (args[1].equals("online")){
            outputOnline = true;
        } else {
            throw new IllegalArgumentException("Only online or offline version");
        }
        System.out.println("PandaScore online: " + inputOnline);
        System.out.println("Imgur Online: " +outputOnline);


        ui.HomeUI(inputOnline,outputOnline);


    }

}
